
on:
  push:
    branches:    
      - 'master'

jobs:          
  build-and-push-docker-image:
    name: Build Docker image and push to Docker registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ghcr.io/alitoufighi/asb-sh-backend:stable
            ghcr.io/alitoufighi/asb-sh-backend:${{ github.RUN_ID }}
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=registry,ref=ghcr.io/alitoufighi/asb-sh-backend
          cache-to: type=registry,ref=ghcr.io/alitoufighi/asb-sh-backend,mode=max

  deploy-aks:
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
    steps:
    - uses: actions-hub/kubectl@master
      name: Backend deployment rolling restart to fetch recently build docker image from docker hub.
      with:
        kubeconfig: ${{ secrets.KUBECONFIG_DATA }}
        args: set image deployment shellhacks-back shellhacks-back=ghcr.io/alitoufighi/asb-sh-backend:${{ github.RUN_ID }}
    
    - uses: actions-hub/kubectl@master
      name: Verify deployment for backend app
      with:
        kubeconfig: ${{ secrets.KUBECONFIG_DATA }}
        args: rollout status deployment/shellhacks-back
